version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=logs
      - WEB_PASSWORD=${WEB_PASSWORD:-}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=logs
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 